/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Flipdish.Client;
using Flipdish.Model;

namespace Flipdish.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStripeCustomConnectApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        RestApiResultStripeConnectedAccount CreateStripeConnectedAccount (string appId, int? bankAccountId);

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        ApiResponse<RestApiResultStripeConnectedAccount> CreateStripeConnectedAccountWithHttpInfo (string appId, int? bankAccountId);
        /// <summary>
        /// Gets a single-use Stripe URL for the given account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        RestApiResultStripeConnectedAccount CreateStripeConnectedAccountLink (string appId, StripeAccountLinkRequest stripeAccountLinkRequest);

        /// <summary>
        /// Gets a single-use Stripe URL for the given account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        ApiResponse<RestApiResultStripeConnectedAccount> CreateStripeConnectedAccountLinkWithHttpInfo (string appId, StripeAccountLinkRequest stripeAccountLinkRequest);
        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        RestApiResultStripeConnectedAccount GetCustomConnectAccount (string appId, int? bankAccountId);

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        ApiResponse<RestApiResultStripeConnectedAccount> GetCustomConnectAccountWithHttpInfo (string appId, int? bankAccountId);
        /// <summary>
        /// Gets the current verification status of the given connected account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        RestApiResultStripeConnectedAccount GetVerificationStatus (string appId, string stripeId);

        /// <summary>
        /// Gets the current verification status of the given connected account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        ApiResponse<RestApiResultStripeConnectedAccount> GetVerificationStatusWithHttpInfo (string appId, string stripeId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> CreateStripeConnectedAccountAsync (string appId, int? bankAccountId);

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> CreateStripeConnectedAccountAsyncWithHttpInfo (string appId, int? bankAccountId);
        /// <summary>
        /// Gets a single-use Stripe URL for the given account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> CreateStripeConnectedAccountLinkAsync (string appId, StripeAccountLinkRequest stripeAccountLinkRequest);

        /// <summary>
        /// Gets a single-use Stripe URL for the given account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> CreateStripeConnectedAccountLinkAsyncWithHttpInfo (string appId, StripeAccountLinkRequest stripeAccountLinkRequest);
        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> GetCustomConnectAccountAsync (string appId, int? bankAccountId);

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> GetCustomConnectAccountAsyncWithHttpInfo (string appId, int? bankAccountId);
        /// <summary>
        /// Gets the current verification status of the given connected account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> GetVerificationStatusAsync (string appId, string stripeId);

        /// <summary>
        /// Gets the current verification status of the given connected account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> GetVerificationStatusAsyncWithHttpInfo (string appId, string stripeId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StripeCustomConnectApi : IStripeCustomConnectApi
    {
        private Flipdish.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StripeCustomConnectApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StripeCustomConnectApi(String basePath)
        {
            this.Configuration = new Flipdish.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Flipdish.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StripeCustomConnectApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StripeCustomConnectApi(Flipdish.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Flipdish.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Flipdish.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Flipdish.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Flipdish.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        public RestApiResultStripeConnectedAccount CreateStripeConnectedAccount (string appId, int? bankAccountId)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = CreateStripeConnectedAccountWithHttpInfo(appId, bankAccountId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        public ApiResponse< RestApiResultStripeConnectedAccount > CreateStripeConnectedAccountWithHttpInfo (string appId, int? bankAccountId)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->CreateStripeConnectedAccount");
            // verify the required parameter 'bankAccountId' is set
            if (bankAccountId == null)
                throw new ApiException(400, "Missing required parameter 'bankAccountId' when calling StripeCustomConnectApi->CreateStripeConnectedAccount");

            var localVarPath = "/api/v1.0/{appId}/customconnect/create-account";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (bankAccountId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "bankAccountId", bankAccountId)); // query parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateStripeConnectedAccount", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        public async System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> CreateStripeConnectedAccountAsync (string appId, int? bankAccountId)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = await CreateStripeConnectedAccountAsyncWithHttpInfo(appId, bankAccountId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> CreateStripeConnectedAccountAsyncWithHttpInfo (string appId, int? bankAccountId)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->CreateStripeConnectedAccount");
            // verify the required parameter 'bankAccountId' is set
            if (bankAccountId == null)
                throw new ApiException(400, "Missing required parameter 'bankAccountId' when calling StripeCustomConnectApi->CreateStripeConnectedAccount");

            var localVarPath = "/api/v1.0/{appId}/customconnect/create-account";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (bankAccountId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "bankAccountId", bankAccountId)); // query parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateStripeConnectedAccount", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Gets a single-use Stripe URL for the given account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        public RestApiResultStripeConnectedAccount CreateStripeConnectedAccountLink (string appId, StripeAccountLinkRequest stripeAccountLinkRequest)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = CreateStripeConnectedAccountLinkWithHttpInfo(appId, stripeAccountLinkRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a single-use Stripe URL for the given account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        public ApiResponse< RestApiResultStripeConnectedAccount > CreateStripeConnectedAccountLinkWithHttpInfo (string appId, StripeAccountLinkRequest stripeAccountLinkRequest)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->CreateStripeConnectedAccountLink");
            // verify the required parameter 'stripeAccountLinkRequest' is set
            if (stripeAccountLinkRequest == null)
                throw new ApiException(400, "Missing required parameter 'stripeAccountLinkRequest' when calling StripeCustomConnectApi->CreateStripeConnectedAccountLink");

            var localVarPath = "/api/v1.0/{appId}/customconnect/create-account-link";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (stripeAccountLinkRequest != null && stripeAccountLinkRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(stripeAccountLinkRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = stripeAccountLinkRequest; // byte array
            }

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateStripeConnectedAccountLink", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Gets a single-use Stripe URL for the given account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        public async System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> CreateStripeConnectedAccountLinkAsync (string appId, StripeAccountLinkRequest stripeAccountLinkRequest)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = await CreateStripeConnectedAccountLinkAsyncWithHttpInfo(appId, stripeAccountLinkRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets a single-use Stripe URL for the given account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeAccountLinkRequest"></param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> CreateStripeConnectedAccountLinkAsyncWithHttpInfo (string appId, StripeAccountLinkRequest stripeAccountLinkRequest)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->CreateStripeConnectedAccountLink");
            // verify the required parameter 'stripeAccountLinkRequest' is set
            if (stripeAccountLinkRequest == null)
                throw new ApiException(400, "Missing required parameter 'stripeAccountLinkRequest' when calling StripeCustomConnectApi->CreateStripeConnectedAccountLink");

            var localVarPath = "/api/v1.0/{appId}/customconnect/create-account-link";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (stripeAccountLinkRequest != null && stripeAccountLinkRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(stripeAccountLinkRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = stripeAccountLinkRequest; // byte array
            }

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateStripeConnectedAccountLink", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        public RestApiResultStripeConnectedAccount GetCustomConnectAccount (string appId, int? bankAccountId)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = GetCustomConnectAccountWithHttpInfo(appId, bankAccountId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        public ApiResponse< RestApiResultStripeConnectedAccount > GetCustomConnectAccountWithHttpInfo (string appId, int? bankAccountId)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->GetCustomConnectAccount");
            // verify the required parameter 'bankAccountId' is set
            if (bankAccountId == null)
                throw new ApiException(400, "Missing required parameter 'bankAccountId' when calling StripeCustomConnectApi->GetCustomConnectAccount");

            var localVarPath = "/api/v1.0/{appId}/customconnect/account";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (bankAccountId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "bankAccountId", bankAccountId)); // query parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomConnectAccount", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        public async System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> GetCustomConnectAccountAsync (string appId, int? bankAccountId)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = await GetCustomConnectAccountAsyncWithHttpInfo(appId, bankAccountId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the Stripe connected account associated with the bank account of bankAccountId, if any 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId">App Name Id</param>
        /// <param name="bankAccountId">Bank Account Id</param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> GetCustomConnectAccountAsyncWithHttpInfo (string appId, int? bankAccountId)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->GetCustomConnectAccount");
            // verify the required parameter 'bankAccountId' is set
            if (bankAccountId == null)
                throw new ApiException(400, "Missing required parameter 'bankAccountId' when calling StripeCustomConnectApi->GetCustomConnectAccount");

            var localVarPath = "/api/v1.0/{appId}/customconnect/account";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (bankAccountId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "bankAccountId", bankAccountId)); // query parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCustomConnectAccount", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Gets the current verification status of the given connected account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>RestApiResultStripeConnectedAccount</returns>
        public RestApiResultStripeConnectedAccount GetVerificationStatus (string appId, string stripeId)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = GetVerificationStatusWithHttpInfo(appId, stripeId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the current verification status of the given connected account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>ApiResponse of RestApiResultStripeConnectedAccount</returns>
        public ApiResponse< RestApiResultStripeConnectedAccount > GetVerificationStatusWithHttpInfo (string appId, string stripeId)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->GetVerificationStatus");
            // verify the required parameter 'stripeId' is set
            if (stripeId == null)
                throw new ApiException(400, "Missing required parameter 'stripeId' when calling StripeCustomConnectApi->GetVerificationStatus");

            var localVarPath = "/api/v1.0/{appId}/customconnect/verification-status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (stripeId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "stripeId", stripeId)); // query parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetVerificationStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

        /// <summary>
        /// Gets the current verification status of the given connected account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>Task of RestApiResultStripeConnectedAccount</returns>
        public async System.Threading.Tasks.Task<RestApiResultStripeConnectedAccount> GetVerificationStatusAsync (string appId, string stripeId)
        {
             ApiResponse<RestApiResultStripeConnectedAccount> localVarResponse = await GetVerificationStatusAsyncWithHttpInfo(appId, stripeId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the current verification status of the given connected account 
        /// </summary>
        /// <exception cref="Flipdish.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="appId"></param>
        /// <param name="stripeId"></param>
        /// <returns>Task of ApiResponse (RestApiResultStripeConnectedAccount)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<RestApiResultStripeConnectedAccount>> GetVerificationStatusAsyncWithHttpInfo (string appId, string stripeId)
        {
            // verify the required parameter 'appId' is set
            if (appId == null)
                throw new ApiException(400, "Missing required parameter 'appId' when calling StripeCustomConnectApi->GetVerificationStatus");
            // verify the required parameter 'stripeId' is set
            if (stripeId == null)
                throw new ApiException(400, "Missing required parameter 'stripeId' when calling StripeCustomConnectApi->GetVerificationStatus");

            var localVarPath = "/api/v1.0/{appId}/customconnect/verification-status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (appId != null) localVarPathParams.Add("appId", this.Configuration.ApiClient.ParameterToString(appId)); // path parameter
            if (stripeId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "stripeId", stripeId)); // query parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetVerificationStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<RestApiResultStripeConnectedAccount>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (RestApiResultStripeConnectedAccount) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(RestApiResultStripeConnectedAccount)));
        }

    }
}
