# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: 1.1$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  nuspec: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'



- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(nuspec)'
    versioningScheme: 'byBuildNumber'



- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
