/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Publish Menu Changes
    /// </summary>
    [DataContract]
    public partial class PublishMenuChanges :  IEquatable<PublishMenuChanges>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublishMenuChanges" /> class.
        /// </summary>
        /// <param name="catalogItemId">Optional Catalog item id.</param>
        /// <param name="menuIds">Optional Collection of Menu id.</param>
        public PublishMenuChanges(string catalogItemId = default(string), List<int?> menuIds = default(List<int?>))
        {
            this.CatalogItemId = catalogItemId;
            this.MenuIds = menuIds;
        }
        
        /// <summary>
        /// Optional Catalog item id
        /// </summary>
        /// <value>Optional Catalog item id</value>
        [DataMember(Name="CatalogItemId", EmitDefaultValue=false)]
        public string CatalogItemId { get; set; }

        /// <summary>
        /// Optional Collection of Menu id
        /// </summary>
        /// <value>Optional Collection of Menu id</value>
        [DataMember(Name="MenuIds", EmitDefaultValue=false)]
        public List<int?> MenuIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublishMenuChanges {\n");
            sb.Append("  CatalogItemId: ").Append(CatalogItemId).Append("\n");
            sb.Append("  MenuIds: ").Append(MenuIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PublishMenuChanges);
        }

        /// <summary>
        /// Returns true if PublishMenuChanges instances are equal
        /// </summary>
        /// <param name="input">Instance of PublishMenuChanges to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublishMenuChanges input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CatalogItemId == input.CatalogItemId ||
                    (this.CatalogItemId != null &&
                    this.CatalogItemId.Equals(input.CatalogItemId))
                ) && 
                (
                    this.MenuIds == input.MenuIds ||
                    this.MenuIds != null &&
                    this.MenuIds.SequenceEqual(input.MenuIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CatalogItemId != null)
                    hashCode = hashCode * 59 + this.CatalogItemId.GetHashCode();
                if (this.MenuIds != null)
                    hashCode = hashCode * 59 + this.MenuIds.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CatalogItemId (string) maxLength
            if(this.CatalogItemId != null && this.CatalogItemId.Length > 30)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CatalogItemId, length must be less than 30.", new [] { "CatalogItemId" });
            }

            // CatalogItemId (string) minLength
            if(this.CatalogItemId != null && this.CatalogItemId.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CatalogItemId, length must be greater than 0.", new [] { "CatalogItemId" });
            }

            yield break;
        }
    }

}
