/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GoogleAddressComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GoogleAddressComponentTests
    {
        // TODO uncomment below to declare an instance variable for GoogleAddressComponent
        //private GoogleAddressComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GoogleAddressComponent
            //instance = new GoogleAddressComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GoogleAddressComponent
        /// </summary>
        [Test]
        public void GoogleAddressComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GoogleAddressComponent
            //Assert.IsInstanceOfType<GoogleAddressComponent> (instance, "variable 'instance' is a GoogleAddressComponent");
        }


        /// <summary>
        /// Test the property 'LongName'
        /// </summary>
        [Test]
        public void LongNameTest()
        {
            // TODO unit test for the property 'LongName'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Test]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }
        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Test]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }

    }

}
