/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RestApiResultOrderBatchingConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestApiResultOrderBatchingConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for RestApiResultOrderBatchingConfiguration
        //private RestApiResultOrderBatchingConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestApiResultOrderBatchingConfiguration
            //instance = new RestApiResultOrderBatchingConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestApiResultOrderBatchingConfiguration
        /// </summary>
        [Test]
        public void RestApiResultOrderBatchingConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestApiResultOrderBatchingConfiguration
            //Assert.IsInstanceOfType<RestApiResultOrderBatchingConfiguration> (instance, "variable 'instance' is a RestApiResultOrderBatchingConfiguration");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
