/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Flipdish.Client.SwaggerDateConverter;

namespace Flipdish.Model
{
    /// <summary>
    /// PayoutReport3PropertyDetails
    /// </summary>
    [DataContract]
    public partial class PayoutReport3PropertyDetails :  IEquatable<PayoutReport3PropertyDetails>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayoutReport3PropertyDetails" /> class.
        /// </summary>
        /// <param name="availableProperties">availableProperties.</param>
        /// <param name="selectedPropertyIds">selectedPropertyIds.</param>
        /// <param name="matchedStoreIds">matchedStoreIds.</param>
        /// <param name="details">details.</param>
        public PayoutReport3PropertyDetails(List<PayoutReport3PropertyFilterOption> availableProperties = default(List<PayoutReport3PropertyFilterOption>), List<string> selectedPropertyIds = default(List<string>), List<int?> matchedStoreIds = default(List<int?>), PayoutReport3Details details = default(PayoutReport3Details))
        {
            this.AvailableProperties = availableProperties;
            this.SelectedPropertyIds = selectedPropertyIds;
            this.MatchedStoreIds = matchedStoreIds;
            this.Details = details;
        }
        
        /// <summary>
        /// Gets or Sets AvailableProperties
        /// </summary>
        [DataMember(Name="AvailableProperties", EmitDefaultValue=false)]
        public List<PayoutReport3PropertyFilterOption> AvailableProperties { get; set; }

        /// <summary>
        /// Gets or Sets SelectedPropertyIds
        /// </summary>
        [DataMember(Name="SelectedPropertyIds", EmitDefaultValue=false)]
        public List<string> SelectedPropertyIds { get; set; }

        /// <summary>
        /// Gets or Sets MatchedStoreIds
        /// </summary>
        [DataMember(Name="MatchedStoreIds", EmitDefaultValue=false)]
        public List<int?> MatchedStoreIds { get; set; }

        /// <summary>
        /// Gets or Sets Details
        /// </summary>
        [DataMember(Name="Details", EmitDefaultValue=false)]
        public PayoutReport3Details Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PayoutReport3PropertyDetails {\n");
            sb.Append("  AvailableProperties: ").Append(AvailableProperties).Append("\n");
            sb.Append("  SelectedPropertyIds: ").Append(SelectedPropertyIds).Append("\n");
            sb.Append("  MatchedStoreIds: ").Append(MatchedStoreIds).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PayoutReport3PropertyDetails);
        }

        /// <summary>
        /// Returns true if PayoutReport3PropertyDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of PayoutReport3PropertyDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PayoutReport3PropertyDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AvailableProperties == input.AvailableProperties ||
                    this.AvailableProperties != null &&
                    this.AvailableProperties.SequenceEqual(input.AvailableProperties)
                ) && 
                (
                    this.SelectedPropertyIds == input.SelectedPropertyIds ||
                    this.SelectedPropertyIds != null &&
                    this.SelectedPropertyIds.SequenceEqual(input.SelectedPropertyIds)
                ) && 
                (
                    this.MatchedStoreIds == input.MatchedStoreIds ||
                    this.MatchedStoreIds != null &&
                    this.MatchedStoreIds.SequenceEqual(input.MatchedStoreIds)
                ) && 
                (
                    this.Details == input.Details ||
                    (this.Details != null &&
                    this.Details.Equals(input.Details))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AvailableProperties != null)
                    hashCode = hashCode * 59 + this.AvailableProperties.GetHashCode();
                if (this.SelectedPropertyIds != null)
                    hashCode = hashCode * 59 + this.SelectedPropertyIds.GetHashCode();
                if (this.MatchedStoreIds != null)
                    hashCode = hashCode * 59 + this.MatchedStoreIds.GetHashCode();
                if (this.Details != null)
                    hashCode = hashCode * 59 + this.Details.GetHashCode();
                return hashCode;
            }
        }
    }

}
