/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Flipdish.Client.SwaggerDateConverter;

namespace Flipdish.Model
{
    /// <summary>
    /// An SMS conversation item for admin user chat.
    /// </summary>
    [DataContract]
    public partial class UserSmsChatItem :  IEquatable<UserSmsChatItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserSmsChatItem" /> class.
        /// </summary>
        /// <param name="smsConversationItemId">SmsConversationItemId..</param>
        /// <param name="direction">Direction..</param>
        /// <param name="from">From..</param>
        /// <param name="text">Text..</param>
        /// <param name="tsSentReceivedUtc">TsSentReceivedUtc..</param>
        public UserSmsChatItem(int? smsConversationItemId = default(int?), string direction = default(string), string from = default(string), string text = default(string), DateTime? tsSentReceivedUtc = default(DateTime?))
        {
            this.SmsConversationItemId = smsConversationItemId;
            this.Direction = direction;
            this.From = from;
            this.Text = text;
            this.TsSentReceivedUtc = tsSentReceivedUtc;
        }
        
        /// <summary>
        /// SmsConversationItemId.
        /// </summary>
        /// <value>SmsConversationItemId.</value>
        [DataMember(Name="SmsConversationItemId", EmitDefaultValue=false)]
        public int? SmsConversationItemId { get; set; }

        /// <summary>
        /// Direction.
        /// </summary>
        /// <value>Direction.</value>
        [DataMember(Name="Direction", EmitDefaultValue=false)]
        public string Direction { get; set; }

        /// <summary>
        /// From.
        /// </summary>
        /// <value>From.</value>
        [DataMember(Name="From", EmitDefaultValue=false)]
        public string From { get; set; }

        /// <summary>
        /// Text.
        /// </summary>
        /// <value>Text.</value>
        [DataMember(Name="Text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// TsSentReceivedUtc.
        /// </summary>
        /// <value>TsSentReceivedUtc.</value>
        [DataMember(Name="TsSentReceivedUtc", EmitDefaultValue=false)]
        public DateTime? TsSentReceivedUtc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserSmsChatItem {\n");
            sb.Append("  SmsConversationItemId: ").Append(SmsConversationItemId).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  TsSentReceivedUtc: ").Append(TsSentReceivedUtc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserSmsChatItem);
        }

        /// <summary>
        /// Returns true if UserSmsChatItem instances are equal
        /// </summary>
        /// <param name="input">Instance of UserSmsChatItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserSmsChatItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SmsConversationItemId == input.SmsConversationItemId ||
                    (this.SmsConversationItemId != null &&
                    this.SmsConversationItemId.Equals(input.SmsConversationItemId))
                ) && 
                (
                    this.Direction == input.Direction ||
                    (this.Direction != null &&
                    this.Direction.Equals(input.Direction))
                ) && 
                (
                    this.From == input.From ||
                    (this.From != null &&
                    this.From.Equals(input.From))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.TsSentReceivedUtc == input.TsSentReceivedUtc ||
                    (this.TsSentReceivedUtc != null &&
                    this.TsSentReceivedUtc.Equals(input.TsSentReceivedUtc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SmsConversationItemId != null)
                    hashCode = hashCode * 59 + this.SmsConversationItemId.GetHashCode();
                if (this.Direction != null)
                    hashCode = hashCode * 59 + this.Direction.GetHashCode();
                if (this.From != null)
                    hashCode = hashCode * 59 + this.From.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.TsSentReceivedUtc != null)
                    hashCode = hashCode * 59 + this.TsSentReceivedUtc.GetHashCode();
                return hashCode;
            }
        }
    }

}
