/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Flipdish.Client.SwaggerDateConverter;

namespace Flipdish.Model
{
    /// <summary>
    /// Voucher
    /// </summary>
    [DataContract]
    public partial class Voucher :  IEquatable<Voucher>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets VoucherType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VoucherTypeEnum
        {
            
            /// <summary>
            /// Enum PercentageDiscount for "PercentageDiscount"
            /// </summary>
            [EnumMember(Value = "PercentageDiscount")]
            PercentageDiscount,
            
            /// <summary>
            /// Enum LumpDiscount for "LumpDiscount"
            /// </summary>
            [EnumMember(Value = "LumpDiscount")]
            LumpDiscount,
            
            /// <summary>
            /// Enum AddItem for "AddItem"
            /// </summary>
            [EnumMember(Value = "AddItem")]
            AddItem,
            
            /// <summary>
            /// Enum CreditNote for "CreditNote"
            /// </summary>
            [EnumMember(Value = "CreditNote")]
            CreditNote
        }

        /// <summary>
        /// Gets or Sets VoucherSubType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VoucherSubTypeEnum
        {
            
            /// <summary>
            /// Enum None for "None"
            /// </summary>
            [EnumMember(Value = "None")]
            None,
            
            /// <summary>
            /// Enum SignUp for "SignUp"
            /// </summary>
            [EnumMember(Value = "SignUp")]
            SignUp,
            
            /// <summary>
            /// Enum Loyalty for "Loyalty"
            /// </summary>
            [EnumMember(Value = "Loyalty")]
            Loyalty,
            
            /// <summary>
            /// Enum Loyalty25 for "Loyalty25"
            /// </summary>
            [EnumMember(Value = "Loyalty25")]
            Loyalty25,
            
            /// <summary>
            /// Enum Retention for "Retention"
            /// </summary>
            [EnumMember(Value = "Retention")]
            Retention,
            
            /// <summary>
            /// Enum SecondaryRetention for "SecondaryRetention"
            /// </summary>
            [EnumMember(Value = "SecondaryRetention")]
            SecondaryRetention,
            
            /// <summary>
            /// Enum Custom for "Custom"
            /// </summary>
            [EnumMember(Value = "Custom")]
            Custom
        }

        /// <summary>
        /// Gets or Sets VoucherPayer
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VoucherPayerEnum
        {
            
            /// <summary>
            /// Enum Flipdish for "Flipdish"
            /// </summary>
            [EnumMember(Value = "Flipdish")]
            Flipdish,
            
            /// <summary>
            /// Enum Store for "Store"
            /// </summary>
            [EnumMember(Value = "Store")]
            Store
        }

        /// <summary>
        /// Gets or Sets VoucherType
        /// </summary>
        [DataMember(Name="VoucherType", EmitDefaultValue=false)]
        public VoucherTypeEnum? VoucherType { get; set; }
        /// <summary>
        /// Gets or Sets VoucherSubType
        /// </summary>
        [DataMember(Name="VoucherSubType", EmitDefaultValue=false)]
        public VoucherSubTypeEnum? VoucherSubType { get; set; }
        /// <summary>
        /// Gets or Sets VoucherPayer
        /// </summary>
        [DataMember(Name="VoucherPayer", EmitDefaultValue=false)]
        public VoucherPayerEnum? VoucherPayer { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Voucher" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Voucher() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Voucher" /> class.
        /// </summary>
        /// <param name="VoucherId">VoucherId.</param>
        /// <param name="VoucherType">VoucherType.</param>
        /// <param name="IsEnabled">IsEnabled.</param>
        /// <param name="IsUsedUp">IsUsedUp.</param>
        /// <param name="VoucherSubType">VoucherSubType.</param>
        /// <param name="PublicDescription">PublicDescription.</param>
        /// <param name="PrivateDescription">PrivateDescription.</param>
        /// <param name="ValidFrom">ValidFrom.</param>
        /// <param name="Expiry">Expiry.</param>
        /// <param name="VoucherPayer">VoucherPayer.</param>
        /// <param name="IsVisibleToStore">IsVisibleToStore.</param>
        /// <param name="IsReusable">IsReusable.</param>
        /// <param name="IsValidForDeliveryOrders">IsValidForDeliveryOrders.</param>
        /// <param name="IsValidForPickupOrders">IsValidForPickupOrders.</param>
        /// <param name="IsValidForCardOrders">IsValidForCardOrders.</param>
        /// <param name="IsValidForCashOrders">IsValidForCashOrders.</param>
        /// <param name="IsValidForFirstOrderOnly">IsValidForFirstOrderOnly.</param>
        /// <param name="MinimumOrderAmount">MinimumOrderAmount.</param>
        /// <param name="IsValidOncePerCustomer">IsValidOncePerCustomer.</param>
        /// <param name="AutoApply">AutoApply.</param>
        /// <param name="AutoApplyOrder">AutoApplyOrder.</param>
        /// <param name="IncludeDeliveryFee">IncludeDeliveryFee.</param>
        /// <param name="Code">Code (required).</param>
        public Voucher(int? VoucherId = default(int?), VoucherTypeEnum? VoucherType = default(VoucherTypeEnum?), bool? IsEnabled = default(bool?), bool? IsUsedUp = default(bool?), VoucherSubTypeEnum? VoucherSubType = default(VoucherSubTypeEnum?), string PublicDescription = default(string), string PrivateDescription = default(string), DateTime? ValidFrom = default(DateTime?), DateTime? Expiry = default(DateTime?), VoucherPayerEnum? VoucherPayer = default(VoucherPayerEnum?), bool? IsVisibleToStore = default(bool?), bool? IsReusable = default(bool?), bool? IsValidForDeliveryOrders = default(bool?), bool? IsValidForPickupOrders = default(bool?), bool? IsValidForCardOrders = default(bool?), bool? IsValidForCashOrders = default(bool?), bool? IsValidForFirstOrderOnly = default(bool?), double? MinimumOrderAmount = default(double?), bool? IsValidOncePerCustomer = default(bool?), bool? AutoApply = default(bool?), int? AutoApplyOrder = default(int?), bool? IncludeDeliveryFee = default(bool?), string Code = default(string))
        {
            // to ensure "Code" is required (not null)
            if (Code == null)
            {
                throw new InvalidDataException("Code is a required property for Voucher and cannot be null");
            }
            else
            {
                this.Code = Code;
            }
            this.VoucherId = VoucherId;
            this.VoucherType = VoucherType;
            this.IsEnabled = IsEnabled;
            this.IsUsedUp = IsUsedUp;
            this.VoucherSubType = VoucherSubType;
            this.PublicDescription = PublicDescription;
            this.PrivateDescription = PrivateDescription;
            this.ValidFrom = ValidFrom;
            this.Expiry = Expiry;
            this.VoucherPayer = VoucherPayer;
            this.IsVisibleToStore = IsVisibleToStore;
            this.IsReusable = IsReusable;
            this.IsValidForDeliveryOrders = IsValidForDeliveryOrders;
            this.IsValidForPickupOrders = IsValidForPickupOrders;
            this.IsValidForCardOrders = IsValidForCardOrders;
            this.IsValidForCashOrders = IsValidForCashOrders;
            this.IsValidForFirstOrderOnly = IsValidForFirstOrderOnly;
            this.MinimumOrderAmount = MinimumOrderAmount;
            this.IsValidOncePerCustomer = IsValidOncePerCustomer;
            this.AutoApply = AutoApply;
            this.AutoApplyOrder = AutoApplyOrder;
            this.IncludeDeliveryFee = IncludeDeliveryFee;
        }
        
        /// <summary>
        /// Gets or Sets VoucherId
        /// </summary>
        [DataMember(Name="VoucherId", EmitDefaultValue=false)]
        public int? VoucherId { get; set; }


        /// <summary>
        /// Gets or Sets IsEnabled
        /// </summary>
        [DataMember(Name="IsEnabled", EmitDefaultValue=false)]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// Gets or Sets IsUsedUp
        /// </summary>
        [DataMember(Name="IsUsedUp", EmitDefaultValue=false)]
        public bool? IsUsedUp { get; set; }


        /// <summary>
        /// Gets or Sets PublicDescription
        /// </summary>
        [DataMember(Name="PublicDescription", EmitDefaultValue=false)]
        public string PublicDescription { get; set; }

        /// <summary>
        /// Gets or Sets PrivateDescription
        /// </summary>
        [DataMember(Name="PrivateDescription", EmitDefaultValue=false)]
        public string PrivateDescription { get; set; }

        /// <summary>
        /// Gets or Sets ValidFrom
        /// </summary>
        [DataMember(Name="ValidFrom", EmitDefaultValue=false)]
        public DateTime? ValidFrom { get; set; }

        /// <summary>
        /// Gets or Sets Expiry
        /// </summary>
        [DataMember(Name="Expiry", EmitDefaultValue=false)]
        public DateTime? Expiry { get; set; }


        /// <summary>
        /// Gets or Sets IsVisibleToStore
        /// </summary>
        [DataMember(Name="IsVisibleToStore", EmitDefaultValue=false)]
        public bool? IsVisibleToStore { get; set; }

        /// <summary>
        /// Gets or Sets IsReusable
        /// </summary>
        [DataMember(Name="IsReusable", EmitDefaultValue=false)]
        public bool? IsReusable { get; set; }

        /// <summary>
        /// Gets or Sets IsValidForDeliveryOrders
        /// </summary>
        [DataMember(Name="IsValidForDeliveryOrders", EmitDefaultValue=false)]
        public bool? IsValidForDeliveryOrders { get; set; }

        /// <summary>
        /// Gets or Sets IsValidForPickupOrders
        /// </summary>
        [DataMember(Name="IsValidForPickupOrders", EmitDefaultValue=false)]
        public bool? IsValidForPickupOrders { get; set; }

        /// <summary>
        /// Gets or Sets IsValidForCardOrders
        /// </summary>
        [DataMember(Name="IsValidForCardOrders", EmitDefaultValue=false)]
        public bool? IsValidForCardOrders { get; set; }

        /// <summary>
        /// Gets or Sets IsValidForCashOrders
        /// </summary>
        [DataMember(Name="IsValidForCashOrders", EmitDefaultValue=false)]
        public bool? IsValidForCashOrders { get; set; }

        /// <summary>
        /// Gets or Sets IsValidForFirstOrderOnly
        /// </summary>
        [DataMember(Name="IsValidForFirstOrderOnly", EmitDefaultValue=false)]
        public bool? IsValidForFirstOrderOnly { get; set; }

        /// <summary>
        /// Gets or Sets MinimumOrderAmount
        /// </summary>
        [DataMember(Name="MinimumOrderAmount", EmitDefaultValue=false)]
        public double? MinimumOrderAmount { get; set; }

        /// <summary>
        /// Gets or Sets IsValidOncePerCustomer
        /// </summary>
        [DataMember(Name="IsValidOncePerCustomer", EmitDefaultValue=false)]
        public bool? IsValidOncePerCustomer { get; set; }

        /// <summary>
        /// Gets or Sets AutoApply
        /// </summary>
        [DataMember(Name="AutoApply", EmitDefaultValue=false)]
        public bool? AutoApply { get; set; }

        /// <summary>
        /// Gets or Sets AutoApplyOrder
        /// </summary>
        [DataMember(Name="AutoApplyOrder", EmitDefaultValue=false)]
        public int? AutoApplyOrder { get; set; }

        /// <summary>
        /// Gets or Sets IncludeDeliveryFee
        /// </summary>
        [DataMember(Name="IncludeDeliveryFee", EmitDefaultValue=false)]
        public bool? IncludeDeliveryFee { get; set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name="Code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Voucher {\n");
            sb.Append("  VoucherId: ").Append(VoucherId).Append("\n");
            sb.Append("  VoucherType: ").Append(VoucherType).Append("\n");
            sb.Append("  IsEnabled: ").Append(IsEnabled).Append("\n");
            sb.Append("  IsUsedUp: ").Append(IsUsedUp).Append("\n");
            sb.Append("  VoucherSubType: ").Append(VoucherSubType).Append("\n");
            sb.Append("  PublicDescription: ").Append(PublicDescription).Append("\n");
            sb.Append("  PrivateDescription: ").Append(PrivateDescription).Append("\n");
            sb.Append("  ValidFrom: ").Append(ValidFrom).Append("\n");
            sb.Append("  Expiry: ").Append(Expiry).Append("\n");
            sb.Append("  VoucherPayer: ").Append(VoucherPayer).Append("\n");
            sb.Append("  IsVisibleToStore: ").Append(IsVisibleToStore).Append("\n");
            sb.Append("  IsReusable: ").Append(IsReusable).Append("\n");
            sb.Append("  IsValidForDeliveryOrders: ").Append(IsValidForDeliveryOrders).Append("\n");
            sb.Append("  IsValidForPickupOrders: ").Append(IsValidForPickupOrders).Append("\n");
            sb.Append("  IsValidForCardOrders: ").Append(IsValidForCardOrders).Append("\n");
            sb.Append("  IsValidForCashOrders: ").Append(IsValidForCashOrders).Append("\n");
            sb.Append("  IsValidForFirstOrderOnly: ").Append(IsValidForFirstOrderOnly).Append("\n");
            sb.Append("  MinimumOrderAmount: ").Append(MinimumOrderAmount).Append("\n");
            sb.Append("  IsValidOncePerCustomer: ").Append(IsValidOncePerCustomer).Append("\n");
            sb.Append("  AutoApply: ").Append(AutoApply).Append("\n");
            sb.Append("  AutoApplyOrder: ").Append(AutoApplyOrder).Append("\n");
            sb.Append("  IncludeDeliveryFee: ").Append(IncludeDeliveryFee).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Voucher);
        }

        /// <summary>
        /// Returns true if Voucher instances are equal
        /// </summary>
        /// <param name="other">Instance of Voucher to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Voucher other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.VoucherId == other.VoucherId ||
                    this.VoucherId != null &&
                    this.VoucherId.Equals(other.VoucherId)
                ) && 
                (
                    this.VoucherType == other.VoucherType ||
                    this.VoucherType != null &&
                    this.VoucherType.Equals(other.VoucherType)
                ) && 
                (
                    this.IsEnabled == other.IsEnabled ||
                    this.IsEnabled != null &&
                    this.IsEnabled.Equals(other.IsEnabled)
                ) && 
                (
                    this.IsUsedUp == other.IsUsedUp ||
                    this.IsUsedUp != null &&
                    this.IsUsedUp.Equals(other.IsUsedUp)
                ) && 
                (
                    this.VoucherSubType == other.VoucherSubType ||
                    this.VoucherSubType != null &&
                    this.VoucherSubType.Equals(other.VoucherSubType)
                ) && 
                (
                    this.PublicDescription == other.PublicDescription ||
                    this.PublicDescription != null &&
                    this.PublicDescription.Equals(other.PublicDescription)
                ) && 
                (
                    this.PrivateDescription == other.PrivateDescription ||
                    this.PrivateDescription != null &&
                    this.PrivateDescription.Equals(other.PrivateDescription)
                ) && 
                (
                    this.ValidFrom == other.ValidFrom ||
                    this.ValidFrom != null &&
                    this.ValidFrom.Equals(other.ValidFrom)
                ) && 
                (
                    this.Expiry == other.Expiry ||
                    this.Expiry != null &&
                    this.Expiry.Equals(other.Expiry)
                ) && 
                (
                    this.VoucherPayer == other.VoucherPayer ||
                    this.VoucherPayer != null &&
                    this.VoucherPayer.Equals(other.VoucherPayer)
                ) && 
                (
                    this.IsVisibleToStore == other.IsVisibleToStore ||
                    this.IsVisibleToStore != null &&
                    this.IsVisibleToStore.Equals(other.IsVisibleToStore)
                ) && 
                (
                    this.IsReusable == other.IsReusable ||
                    this.IsReusable != null &&
                    this.IsReusable.Equals(other.IsReusable)
                ) && 
                (
                    this.IsValidForDeliveryOrders == other.IsValidForDeliveryOrders ||
                    this.IsValidForDeliveryOrders != null &&
                    this.IsValidForDeliveryOrders.Equals(other.IsValidForDeliveryOrders)
                ) && 
                (
                    this.IsValidForPickupOrders == other.IsValidForPickupOrders ||
                    this.IsValidForPickupOrders != null &&
                    this.IsValidForPickupOrders.Equals(other.IsValidForPickupOrders)
                ) && 
                (
                    this.IsValidForCardOrders == other.IsValidForCardOrders ||
                    this.IsValidForCardOrders != null &&
                    this.IsValidForCardOrders.Equals(other.IsValidForCardOrders)
                ) && 
                (
                    this.IsValidForCashOrders == other.IsValidForCashOrders ||
                    this.IsValidForCashOrders != null &&
                    this.IsValidForCashOrders.Equals(other.IsValidForCashOrders)
                ) && 
                (
                    this.IsValidForFirstOrderOnly == other.IsValidForFirstOrderOnly ||
                    this.IsValidForFirstOrderOnly != null &&
                    this.IsValidForFirstOrderOnly.Equals(other.IsValidForFirstOrderOnly)
                ) && 
                (
                    this.MinimumOrderAmount == other.MinimumOrderAmount ||
                    this.MinimumOrderAmount != null &&
                    this.MinimumOrderAmount.Equals(other.MinimumOrderAmount)
                ) && 
                (
                    this.IsValidOncePerCustomer == other.IsValidOncePerCustomer ||
                    this.IsValidOncePerCustomer != null &&
                    this.IsValidOncePerCustomer.Equals(other.IsValidOncePerCustomer)
                ) && 
                (
                    this.AutoApply == other.AutoApply ||
                    this.AutoApply != null &&
                    this.AutoApply.Equals(other.AutoApply)
                ) && 
                (
                    this.AutoApplyOrder == other.AutoApplyOrder ||
                    this.AutoApplyOrder != null &&
                    this.AutoApplyOrder.Equals(other.AutoApplyOrder)
                ) && 
                (
                    this.IncludeDeliveryFee == other.IncludeDeliveryFee ||
                    this.IncludeDeliveryFee != null &&
                    this.IncludeDeliveryFee.Equals(other.IncludeDeliveryFee)
                ) && 
                (
                    this.Code == other.Code ||
                    this.Code != null &&
                    this.Code.Equals(other.Code)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.VoucherId != null)
                    hash = hash * 59 + this.VoucherId.GetHashCode();
                if (this.VoucherType != null)
                    hash = hash * 59 + this.VoucherType.GetHashCode();
                if (this.IsEnabled != null)
                    hash = hash * 59 + this.IsEnabled.GetHashCode();
                if (this.IsUsedUp != null)
                    hash = hash * 59 + this.IsUsedUp.GetHashCode();
                if (this.VoucherSubType != null)
                    hash = hash * 59 + this.VoucherSubType.GetHashCode();
                if (this.PublicDescription != null)
                    hash = hash * 59 + this.PublicDescription.GetHashCode();
                if (this.PrivateDescription != null)
                    hash = hash * 59 + this.PrivateDescription.GetHashCode();
                if (this.ValidFrom != null)
                    hash = hash * 59 + this.ValidFrom.GetHashCode();
                if (this.Expiry != null)
                    hash = hash * 59 + this.Expiry.GetHashCode();
                if (this.VoucherPayer != null)
                    hash = hash * 59 + this.VoucherPayer.GetHashCode();
                if (this.IsVisibleToStore != null)
                    hash = hash * 59 + this.IsVisibleToStore.GetHashCode();
                if (this.IsReusable != null)
                    hash = hash * 59 + this.IsReusable.GetHashCode();
                if (this.IsValidForDeliveryOrders != null)
                    hash = hash * 59 + this.IsValidForDeliveryOrders.GetHashCode();
                if (this.IsValidForPickupOrders != null)
                    hash = hash * 59 + this.IsValidForPickupOrders.GetHashCode();
                if (this.IsValidForCardOrders != null)
                    hash = hash * 59 + this.IsValidForCardOrders.GetHashCode();
                if (this.IsValidForCashOrders != null)
                    hash = hash * 59 + this.IsValidForCashOrders.GetHashCode();
                if (this.IsValidForFirstOrderOnly != null)
                    hash = hash * 59 + this.IsValidForFirstOrderOnly.GetHashCode();
                if (this.MinimumOrderAmount != null)
                    hash = hash * 59 + this.MinimumOrderAmount.GetHashCode();
                if (this.IsValidOncePerCustomer != null)
                    hash = hash * 59 + this.IsValidOncePerCustomer.GetHashCode();
                if (this.AutoApply != null)
                    hash = hash * 59 + this.AutoApply.GetHashCode();
                if (this.AutoApplyOrder != null)
                    hash = hash * 59 + this.AutoApplyOrder.GetHashCode();
                if (this.IncludeDeliveryFee != null)
                    hash = hash * 59 + this.IncludeDeliveryFee.GetHashCode();
                if (this.Code != null)
                    hash = hash * 59 + this.Code.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PublicDescription (string) maxLength
            if(this.PublicDescription != null && this.PublicDescription.Length > 500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PublicDescription, length must be less than 500.", new [] { "PublicDescription" });
            }

            // PublicDescription (string) minLength
            if(this.PublicDescription != null && this.PublicDescription.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PublicDescription, length must be greater than 0.", new [] { "PublicDescription" });
            }

            // PrivateDescription (string) maxLength
            if(this.PrivateDescription != null && this.PrivateDescription.Length > 500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PrivateDescription, length must be less than 500.", new [] { "PrivateDescription" });
            }

            // PrivateDescription (string) minLength
            if(this.PrivateDescription != null && this.PrivateDescription.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PrivateDescription, length must be greater than 0.", new [] { "PrivateDescription" });
            }

            // Code (string) maxLength
            if(this.Code != null && this.Code.Length > 20)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Code, length must be less than 20.", new [] { "Code" });
            }

            // Code (string) minLength
            if(this.Code != null && this.Code.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Code, length must be greater than 0.", new [] { "Code" });
            }

            yield break;
        }
    }

}
