/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flipdish.Api;
using Flipdish.Model;
using Flipdish.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flipdish.Test
{
    /// <summary>
    ///  Class for testing FulfillmentStatesConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FulfillmentStatesConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for FulfillmentStatesConfiguration
        //private FulfillmentStatesConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FulfillmentStatesConfiguration
            //instance = new FulfillmentStatesConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FulfillmentStatesConfiguration
        /// </summary>
        [Test]
        public void FulfillmentStatesConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FulfillmentStatesConfiguration
            //Assert.IsInstanceOfType<FulfillmentStatesConfiguration> (instance, "variable 'instance' is a FulfillmentStatesConfiguration");
        }


        /// <summary>
        /// Test the property 'States'
        /// </summary>
        [Test]
        public void StatesTest()
        {
            // TODO unit test for the property 'States'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'ConfigurationUid'
        /// </summary>
        [Test]
        public void ConfigurationUidTest()
        {
            // TODO unit test for the property 'ConfigurationUid'
        }
        /// <summary>
        /// Test the property 'StoreSelectorType'
        /// </summary>
        [Test]
        public void StoreSelectorTypeTest()
        {
            // TODO unit test for the property 'StoreSelectorType'
        }
        /// <summary>
        /// Test the property 'StoreIds'
        /// </summary>
        [Test]
        public void StoreIdsTest()
        {
            // TODO unit test for the property 'StoreIds'
        }

    }

}
