/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flipdish.Api;
using Flipdish.Model;
using Flipdish.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flipdish.Test
{
    /// <summary>
    ///  Class for testing MenuUpdatedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MenuUpdatedEventTests
    {
        // TODO uncomment below to declare an instance variable for MenuUpdatedEvent
        //private MenuUpdatedEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MenuUpdatedEvent
            //instance = new MenuUpdatedEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MenuUpdatedEvent
        /// </summary>
        [Test]
        public void MenuUpdatedEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MenuUpdatedEvent
            //Assert.IsInstanceOfType<MenuUpdatedEvent> (instance, "variable 'instance' is a MenuUpdatedEvent");
        }


        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Menu'
        /// </summary>
        [Test]
        public void MenuTest()
        {
            // TODO unit test for the property 'Menu'
        }
        /// <summary>
        /// Test the property 'FlipdishEventId'
        /// </summary>
        [Test]
        public void FlipdishEventIdTest()
        {
            // TODO unit test for the property 'FlipdishEventId'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Test]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }

    }

}
