/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flipdish.Api;
using Flipdish.Model;
using Flipdish.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flipdish.Test
{
    /// <summary>
    ///  Class for testing RestApiResultOrderBatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestApiResultOrderBatchTests
    {
        // TODO uncomment below to declare an instance variable for RestApiResultOrderBatch
        //private RestApiResultOrderBatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestApiResultOrderBatch
            //instance = new RestApiResultOrderBatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestApiResultOrderBatch
        /// </summary>
        [Test]
        public void RestApiResultOrderBatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestApiResultOrderBatch
            //Assert.IsInstanceOfType<RestApiResultOrderBatch> (instance, "variable 'instance' is a RestApiResultOrderBatch");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
