/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flipdish.Api;
using Flipdish.Model;
using Flipdish.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flipdish.Test
{
    /// <summary>
    ///  Class for testing StoreKioskSettingModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreKioskSettingModelTests
    {
        // TODO uncomment below to declare an instance variable for StoreKioskSettingModel
        //private StoreKioskSettingModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreKioskSettingModel
            //instance = new StoreKioskSettingModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreKioskSettingModel
        /// </summary>
        [Test]
        public void StoreKioskSettingModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreKioskSettingModel
            //Assert.IsInstanceOfType<StoreKioskSettingModel> (instance, "variable 'instance' is a StoreKioskSettingModel");
        }


        /// <summary>
        /// Test the property 'KioskName'
        /// </summary>
        [Test]
        public void KioskNameTest()
        {
            // TODO unit test for the property 'KioskName'
        }
        /// <summary>
        /// Test the property 'RequireCustomerName'
        /// </summary>
        [Test]
        public void RequireCustomerNameTest()
        {
            // TODO unit test for the property 'RequireCustomerName'
        }
        /// <summary>
        /// Test the property 'RequireCustomerPhoneNumber'
        /// </summary>
        [Test]
        public void RequireCustomerPhoneNumberTest()
        {
            // TODO unit test for the property 'RequireCustomerPhoneNumber'
        }
        /// <summary>
        /// Test the property 'RequestTableNumber'
        /// </summary>
        [Test]
        public void RequestTableNumberTest()
        {
            // TODO unit test for the property 'RequestTableNumber'
        }
        /// <summary>
        /// Test the property 'OfferDineInOrTakeawayOptions'
        /// </summary>
        [Test]
        public void OfferDineInOrTakeawayOptionsTest()
        {
            // TODO unit test for the property 'OfferDineInOrTakeawayOptions'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Test]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }
        /// <summary>
        /// Test the property 'ConfigId'
        /// </summary>
        [Test]
        public void ConfigIdTest()
        {
            // TODO unit test for the property 'ConfigId'
        }
        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Test]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }

    }

}
