/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Flipdish.Api;
using Flipdish.Model;
using Flipdish.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Flipdish.Test
{
    /// <summary>
    ///  Class for testing TipConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TipConfigurationTests
    {
        // TODO uncomment below to declare an instance variable for TipConfiguration
        //private TipConfiguration instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TipConfiguration
            //instance = new TipConfiguration();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TipConfiguration
        /// </summary>
        [Test]
        public void TipConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TipConfiguration
            //Assert.IsInstanceOfType<TipConfiguration> (instance, "variable 'instance' is a TipConfiguration");
        }


        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Test]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Test]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'AllowCustomTips'
        /// </summary>
        [Test]
        public void AllowCustomTipsTest()
        {
            // TODO unit test for the property 'AllowCustomTips'
        }
        /// <summary>
        /// Test the property 'Percentages'
        /// </summary>
        [Test]
        public void PercentagesTest()
        {
            // TODO unit test for the property 'Percentages'
        }
        /// <summary>
        /// Test the property 'DefaultPercentage'
        /// </summary>
        [Test]
        public void DefaultPercentageTest()
        {
            // TODO unit test for the property 'DefaultPercentage'
        }

    }

}
