/* 
 * Flipdish Open API v1.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Flipdish.Client;
using Flipdish.Api;
using Flipdish.Model;

namespace Flipdish.Test
{
    /// <summary>
    ///  Class for testing CatalogItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CatalogItemsApiTests
    {
        private CatalogItemsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CatalogItemsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CatalogItemsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CatalogItemsApi
            //Assert.IsInstanceOfType(typeof(CatalogItemsApi), instance, "instance is a CatalogItemsApi");
        }

        
        /// <summary>
        /// Test GetById
        /// </summary>
        [Test]
        public void GetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string catalogItemId = null;
            //var response = instance.GetById(appId, catalogItemId);
            //Assert.IsInstanceOf<CatalogItem> (response, "response is CatalogItem");
        }
        
        /// <summary>
        /// Test GetItems
        /// </summary>
        [Test]
        public void GetItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //List<string> itemTypes = null;
            //string searchTerm = null;
            //int? page = null;
            //int? limit = null;
            //var response = instance.GetItems(appId, itemTypes, searchTerm, page, limit);
            //Assert.IsInstanceOf<RestApiPaginationResultCatalogItem> (response, "response is RestApiPaginationResultCatalogItem");
        }
        
    }

}
